name: meteo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - cartopy
  - xarray
  - matplotlib
  - cfgrib
  - eccodes
  - herbie-data
  - scipy
  - netcdf4
  - geopandas
  - pandas
  - numpy
  - cdsapi
  - requests
  - folium
  - pip
  - pip:
      - pillow
